import { z, defineCollection } from "astro:content";

const i18nCollection = defineCollection({
  type: "data",
  schema: z.object({
    SEO_TITLE: z.string(),
    SEO_DESCRIPTION: z.string(),
    SEO: z.object({
      ARCHIVO_TITLE: z.string(),
      ARCHIVO_DESCRIPTION: z.string(),
      INFO_TITLE: z.string(),
      INFO_DESCRIPTION: z.string(),
      VOTE_TITLE: z.string(),
      VOTE_DESCRIPTION: z.string(),
    }),
    HEADER_VOTE: z.string(),
    HEADER_INFO: z.string(),
    HEADER_ARCHIVE: z.string(),
    HEADER_BUTTON: z.string(),
    HEADER: z.object({
      LOGO: z.string(),
    }),
    HERO_SUBTITLE: z.string(),
    INTRO_TITLE: z.string(),
    INTRO_TITLE_AFTER_BR: z.string(),
    INTRO_DESCRIPTION_1: z.string(),
    INTRO_DESCRIPTION_2: z.string(),
    INTRO_DESCRIPTION_3: z.string(),
    BENTO_TITLE_1: z.string(),
    BENTO_CONTENT_1: z.string(),
    BENTO_TITLE_2: z.string(),
    BENTO_SUBTITLE_2: z.string(),
    BENTO_CONTENT_2: z.string(),
    BENTO_TITLE_3: z.string(),
    BENTO_SUBTITLE_3: z.string(),
    BENTO_CONTENT_3: z.string(),
    BENTO_TITLE_4: z.string(),
    BENTO_CONTENT_4: z.string(),
    VIDEO_ALT: z.string(),
    VIDEO_BUTTON: z.string(),
    PREFOOTER_VIDEO_TITLE: z.string(),
    ARCHIVO: z.object({
      HERO_TITLE: z.string(),
      HERO_BUTTON: z.string(),
      COUNTER_TITLE: z.string(),
      COUNTER_VIEWS: z.string(),
      COUNTER_NEWS: z.string(),
      COUNTER_MEDIA: z.string(),
    }),
    FOOTER: z.object({
      DISCLAIMER: z.string(),
      LEGAL: z.object({
        TITLE: z.string(),
        NOTICE: z.string(),
        PRIVACY: z.string(),
        COOKIES: z.string(),
        PRIVACY_POLICY: z.string(),
        TOS: z.string(),
      }),
      WEB_MAP: z.object({
        TITLE: z.string(),
        HOME: z.string(),
        INFO: z.string(),
        ARCHIVE: z.string(),
      }),
      PRODUCED_BY: z.string(),
    }),
    INFO_TITLE: z.string(),
    INFO_TITLE_1: z.string(),
    INFO_CONTENT_1_1: z.string(),
    INFO_CONTENT_1_2: z.string(),
    INFO_TITLE_2: z.string(),
    INFO_CONTENT_2_1: z.string(),
    INFO_CONTENT_2_2: z.string(),
    MEDIA_KIT_TITLE: z.string(),
    MEDIA_KIT_SUBTITLE_1: z.string(),
    MEDIA_KIT_SUBTITLE_2: z.string(),
    MEDIA_KIT_SUBTITLE_3: z.string(),
    DOWNLOAD_BUTTON: z.string(),
    COOKIES: z.object({
      POLICIES: z.object({
        TITLE: z.string(),
        DESCRIPTION_1: z.string(),
        DESCRIPTION_2: z.string(),
        DESCRIPTION_3: z.string(),
        DESCRIPTION_4: z.string(),
      }),
      WHAT_IS: z.object({
        TITLE: z.string(),
        DESCRIPTION_1: z.string(),
        DESCRIPTION_2: z.string(),
      }),
      TYPES: z.object({
        TITLE: z.string(),
        DESCRIPTION_1_TITLE: z.string(),
        DESCRIPTION_1: z.string(),
        DESCRIPTION_2_TITLE: z.string(),
        DESCRIPTION_2: z.string(),
        DESCRIPTION_3_TITLE: z.string(),
        DESCRIPTION_3: z.string(),
        DESCRIPTION_4_TITLE: z.string(),
        DESCRIPTION_4: z.string(),
        DESCRIPTION_5_TITLE: z.string(),
        DESCRIPTION_5: z.string(),
        DESCRIPTION_6_TITLE: z.string(),
        DESCRIPTION_6: z.string(),
      }),
      BLOCK: z.object({
        TITLE: z.string(),
        DESCRIPTION_1: z.string(),
        DESCRIPTION_2: z.string(),
        DESCRIPTION_3: z.string(),
        DESCRIPTION_4: z.string(),
        DESCRIPTION_5: z.string(),
        DESCRIPTION_5_URL: z.string(),
        DESCRIPTION_6: z.string(),
        DESCRIPTION_6_URL: z.string(),
        DESCRIPTION_7: z.string(),
        DESCRIPTION_7_URL: z.string(),
        DESCRIPTION_8: z.string(),
        DESCRIPTION_8_URL: z.string(),
        DESCRIPTION_9: z.string(),
        DESCRIPTION_9_URL: z.string(),
        DESCRIPTION_10: z.string(),
        DESCRIPTION_10_URL: z.string(),
        DESCRIPTION_11: z.string(),
      }),
      MORE_INFO: z.object({
        TITLE: z.string(),
        DESCRIPTION_1: z.string(),
        DESCRIPTION_1_URL: z.string(),
        DESCRIPTION_2: z.string(),
        DESCRIPTION_2_URL: z.string(),
        DESCRIPTION_3: z.string(),
        DESCRIPTION_3_URL: z.string(),
      }),
      THIRD_PARTY: z.object({
        TITLE: z.string(),
        DESCRIPTION: z.string(),
      }),
      UPDATES: z.object({
        TITLE: z.string(),
        DESCRIPTION: z.string(),
        DATE: z.string(),
      }),
      SITE_COOKIES: z.object({
        TITLE: z.string(),
        THEAD_NAME: z.string(),
        THEAD_CADUCITY: z.string(),
        THEAD_PROVIDER: z.string(),
        THEAD_FINALITY: z.string(),
        ANALYTICS: z.array(
          z.object({
            NAME: z.string(),
            EXPIRE: z.string(),
            PROVIDER: z.object({
              NAME: z.string(),
              URL: z.string(),
            }),
            OBJECTIVE: z.string(),
            OBJECTIVE_URL: z.string(),
          })
        ),
      }),
    }),
    INFO: z.object({
      TITLE_HERO_1: z.string(),
      TITLE_HERO_2: z.string(),
      GALLERY_TITLE: z.string(),
      GALLERY_TEXT: z.string(),
    }),
  }),
});

export const collections = {
  i18n: i18nCollection,
};
